spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/db_changelog-master.yml